### ISSUE TITLE
Add color to Entry List Table columns

### ISSUE THREAD

**Issue by compass360** [presseddigital/colorit#12]
We're building a site for a client that has multiple entries that rely heavily on colour-coding (each entry needs a distinct colour). The plugin is a huge help in letting our client select between a large list of predefined colours, but being able to see the selected colour in the entry list (like the default color field) would be a huge time saver. Any chance this could be implemented? I'd expect something like a small swatch circle/rectangle alongside the hex/rgb would be ideal.

**Comment by samhibberd** [comment]
This has been added and will be available in 1.0.9.
