### ISSUE TITLE
Better UI for custom color & opacity selection

### ISSUE THREAD

**Issue by proimage** [presseddigital/colorit#17]
As seen in the picture below (with only white and black as predefined options), there are a couple of issues with the interface. For one, the custom hex field relies on the placeholder parameter value to indicate what the field is for, rather than a proper `<label>`. More importantly than that though, the opacity field starts out with "100" and no indication of why that number is there or what it's for... not even in a placeholder.

![image](https://user-images.githubusercontent.com/1027523/76625902-dc816000-6540-11ea-8557-7de81dc81c9c.png)

**Comment by proimage** [comment]
Shameless bump! This really needs to be addressed IMO.

**Comment by proimage** [comment]
*bump *

**Comment by ben-callaway** [comment]
Thanks. Fixed in 1.1.0 82872ca

**Comment by ben-callaway** [comment]
Will investigate labelling 👍

**Comment by ben-callaway** [comment]
Label option added in c6ab399a

<img width="440" alt="Screenshot 2021-07-26 at 11 16 59" src="https://user-images.githubusercontent.com/7083462/126973863-66d1e8bc-fb6c-4b1d-8885-8dfd654dee60.png">
