### ISSUE TITLE
Updating to 1.0.9 breaks site

### ISSUE THREAD

**Issue by mediagirl** [presseddigital/colorit#19]
Upgrading a site to use Colorit 1.0.9 breaks all the things.

This is the error on the Preset config page:
https://www.screencast.com/t/265OEjLfv 

This is the error on the field in an entry:
https://www.screencast.com/t/TpjohfOqqu

From what I can tell the problem is that the plugin files moved locations in the vendor file... 
FROM fruitstudios/colorit 
TO presseddigital/colorit

I put the fruitstudios/colorit back into place but the errors persist.

How can I fix this without uninstalling the plugin, reinstalling it, resetting everything up and editing all the entries?

**Comment by richhayler** [comment]
I've also just upgraded (and paid to renew my annual subscription) and experiencing similar issues. Navigating to an entry that contains the colourist field shows this error where the field should be "Unable to find component class 'fruitstudios\colorit\fields\ColoritField'."

Navigating to the plugin presets displays "server error" within the control panel.

**Comment by mediagirl** [comment]
Rich, 
I fixed by editing the DB directly with these changes:

1. **colorit_presets** table, change **type** to "presseddigital\colorit\fields\ColoritField"

2. **fields** table, sort **type** column to group fields by type, change all using "fruitstudios\colorit\fields\ColoritField" to "presseddigital\colorit\fields\ColoritField"

Anna

**Comment by brandonkelly** [comment]
If you make that change and you are using the project config, make sure you run `./craft project-config/rebuild` after running the DB query.

**Comment by richhayler** [comment]
Thank you both working now :)

**Comment by samhibberd** [comment]
Fixed in 1.0.9.1, thanks @brandonkelly.

**Comment by mediagirl** [comment]
Thank you Brandon and Sam!
