### ISSUE TITLE
Ability to set a default color for a field?

### ISSUE THREAD

**Issue by proimage** [presseddigital/colorit#23]
Seems to me there should be a way to set a default color that will be selected when creating new entries. Currently there seems no way to do so, neither for custom field colors, nor for preset color palettes.

**Comment by cakleimeier** [comment]
I'm also running into this issue; when creating a new field using a preset color palette, it _appears_ that you have the option to select the default color for that particular field, but the functionality doesn't actually work. You can't actually select a color.

**Comment by cakleimeier** [comment]
Has there been any progress on this issue? It's still a problem for me, despite having tried many other solutions suggested in other recent issues.

**Comment by proimage** [comment]
* bump *

**Comment by ben-callaway** [comment]
You can set a default when creating a preset, or a new field.

<img width="784" alt="Screenshot 2021-07-26 at 17 29 30" src="https://user-images.githubusercontent.com/7083462/127025877-912acd92-ccdc-459a-ac34-81cc1c3237e0.png">

Under Default Color, enter the desired default color handle (electricViolet in my example), when a new entry is created the default color will be pre selected...

<img width="384" alt="Screenshot 2021-07-26 at 17 28 58" src="https://user-images.githubusercontent.com/7083462/127026092-afab6c2c-e2c3-49b5-9769-490af2f281bb.png">
