### ISSUE TITLE
Craft 4 version?

### ISSUE THREAD

**Issue by mikewink** [presseddigital/colorit#40]
Hello busy developers,

now that Craft 4 is officially a thing, I wanted to ask if ColorIt will be available for Craft 4 as well? We use your plugin in almost all of our projects and like it a lot. Thank you very much for any, hopefully positive, info. :)

Best regards

Mike

**Comment by samhibberd** [comment]
Bar some styling the craft 4 version is ready to test, be great to get any feedback / issues from anyone here who has time to test: 

https://github.com/presseddigital/colorit/tree/develop-v4

**Comment by mikewink** [comment]
Ohh that's great. Is this a straight upgrade to Craft 4 with the exact same feature set or has there been some changes to look out for?

**Comment by samhibberd** [comment]
Just a straight upgrade for now, but hoping to find some time to add features for sure. 

Anything specific that you are looking out for??

**Comment by mikewink** [comment]
> Anything specific that you are looking out for??

The most important feature that we miss is multi-site support. We have a lot of clients that love the multi-site functionality for a big main site and smaller "satellite" sites. Most of them come with their own colors (Corporate Design).

A second feature we use a lot too are gradients or at least two color sets. In the case of a gradient, it would be the start and end colors. In case of a set, we often use them for background color and foreground color. Or another use case could be background color and border color.

Other than that, I'm very happy with the plugin. :)

**Comment by rene-haefliger** [comment]
Hello, when will the plugin be final available for Craft 4?

**Comment by sunscreem** [comment]
@samhibberd I've installed the devlop-v4 version on a site that had the plugin before, and no issues found at all. 👌

**Comment by patrikalienus** [comment]
Any ETA on a Craft 4 compatible version?

**Comment by rene-haefliger** [comment]
We are using the plugin with Craft 4 without any problems. Is there anything against releasing the plugin officially for Craft 4?

**Comment by samhibberd** [comment]
See [4.0.0](https://github.com/presseddigital/colorit/releases/tag/4.0.0)
