### ISSUE TITLE
Craft 5 Version?

### ISSUE THREAD

**Issue by CreateSean** [presseddigital/colorit#43]
Do you have plans to release a Craft 5 version of this plugin?

**Comment by ben-callaway** [comment]
It's in the works!

**Comment by richhayler** [comment]
Hey @ben-callaway, do you have a rough ETA for Craft 5 compatibility? This is the only paid plugin I regularly use that hasn't yet been updated for Craft 5 - appreciating v5 has only been out for a month ;)

**Comment by niemie7** [comment]
@ben-callaway put me in the same boat, anxious and waiting to buy the Craft 5 version!

**Comment by CreateSean** [comment]
@ben-callaway it's been two months. Do you have an ETA on when this will be ready?

**Comment by samhibberd** [comment]
@CreateSean we’ve finished the migration and testing has uncovered a couple of small things that we are working though. Hopefully we should have it ready for release tomorrow / Friday.

**Comment by CreateSean** [comment]
> @CreateSean we’ve finished the migration and testing has uncovered a couple of small things that we are working though. Hopefully we should have it ready for release tomorrow / Friday.

That's awesome. Looking forward to the release.

**Comment by richhayler** [comment]
> @CreateSean we’ve finished the migration and testing has uncovered a couple of small things that we are working though. Hopefully we should have it ready for release tomorrow / Friday.

Can't wait for this update. Hopefully it will be ready soon :)

**Comment by ben-callaway** [comment]
Released! 🎉
